---
title: "The Associations of Mean Glucose and Time in Range from Continuous Glucose Monitoring with HbA1c in Adults with Type 2 Diabetes"
type: "brief report"
author: "Selvin, Wang, Rooney, Echouffo-Tcheugui, Fang, Zeger, Sartini, Tang, Coresh, Aurora, & Punjabi"
year: "2023"
publication: "Diabetes Technology and Therapeutics"
doi: "https://doi.org/10.1089/dia.2022.0178"
toc: false
categories:
  - CGM
---

## Citation (APA 7)

> Selvin, E., Wang, D., Rooney, M. R., Echouffo-Tcheugui, J., Fang, M., Zeger, S., Sartini, J., Tang, O., Coresh, J., Aurora, R. N., & Punjabi, N. M. (2023). The Associations of Mean Glucose and Time in Range from Continuous Glucose Monitoring with HbA1c in Adults with Type 2 Diabetes. Diabetes technology & therapeutics, 25(1), 86--90. https://doi.org/10.1089/dia.2022.0178

## Abstract

Associations of mean glucose and time in range (70--180 mg/dL) from continuous glucose monitoring (CGM) with HbA1c in adults with type 2 diabetes are not well characterized. We conducted a secondary analysis of 186 participants from the Hyperglycemic Profiles in Obstructive Sleep Apnea (HYPNOS) trial. Participants simultaneously wore Dexcom G4 and Abbott Libre Pro CGM sensors up to 4 weeks. Mean HbA1c was 7.7% (SD, 1.3). There were strong negative Pearson's correlations of HbA1c with CGM time in range (−0.79, Abbott; −0.81, Dexcom) and strong positive correlations with CGM mean glucose (Dexcom, 0.84; Abbott, 0.82). However, there were large differences in CGM mean glucose (±20 mg/dL) and time in range (±14%) at any given HbA1c value. Mean glucose and HbA1c are strongly correlated in type 2 diabetes patients not taking insulin but discordance is evident at the individual level. Clinicians should expect discordance and use HbA1c and CGM in a complementary manner. ClinicalTrials.gov Identifier: NCT02454153
