---
title: "Within-person and between-sensor variability in continuous glucose monitoring metrics"
type: "brief report"
author: "Selvin, Wang, Rooney, Fang, Echouffo-Tcheugui, Zeger, Sartini, Tang, Coresh, Aurora, & Punjabi"
year: "2023"
publication: "Clinical Chemistry"
doi: "https://doi.org/10.1093/clinchem/hvac192"
toc: false
categories:
  - CGM
---

## Citation (APA 7)

> Selvin, E., Wang, D., Rooney, M. R., Fang, M., Echouffo-Tcheugui, J. B., Zeger, S., Sartini, J., Tang, O., Coresh, J., Nisha Aurora, R., & Punjabi, N. M. (2023). Within-Person and Between-Sensor Variability in Continuous Glucose Monitoring Metrics. Clinical chemistry, 69(2), 180--188. https://doi.org/10.1093/clinchem/hvac192

## Abstract

Background: The within-person and between-sensor variability of metrics from different interstitial continuous glucose monitoring (CGM) sensors in adults with type 2 diabetes not taking insulin is unclear. Methods: Secondary analysis of data from 172 participants from the HYPNOS randomized clinical trial. Participants simultaneously wore Dexcom G4 and Abbott Libre Pro CGM sensors for up to 2-weeks at baseline and, again, at the 3-month follow-up visit. Results: At baseline (up to 2-weeks of CGM), mean glucose for both the Abbot and Dexcom sensors was approximately 150 mg/dl and time-in-range (70-180 mg/dL) was just below 80%. When comparing the same sensor at two different time points (two 2-week wear periods, 3 months apart), the within-person variability (CVw) in mean glucose was 17.4% (Abbott) and 14.2% (Dexcom). CVw for percent time-in-range: 20.1% (Abbott) and 18.6% (Dexcom). At baseline, the Pearson's correlation of mean glucose from the two sensors worn simultaneously was r=0.86, root mean squared error (RMSE), 13 mg/dL; for time-in-range, r=0.88, RMSE 8%-points. Conclusions: Substantial variation was observed within sensors over time and across two different sensors worn simultaneously on the same individuals. Clinicians should be aware of this variability when using CGM technology to make clinical decisions.
