project:
  title: "Sartini-Stats"
  type: website
  output-dir: docs

website:
  title: "Sartini-Stats"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Research/Teaching
      - href: cv_host.qmd
        text: CV
      - href: pubs.qmd
        text: Publications
      - href: soft.qmd
        text: Software

format:
  html:
    theme: sandstone
    css: resources/styles/styles.css
    toc: true
    page-layout: full

editor: visual

execute: 
  freeze: auto
