---
title: "Multilevel functional data analysis modeling of human glucose response to meal intake"
type: "article"
author: "Matabuena, Sartini, & Gude"
year: "2024"
publication: "ArXiv"
preprint: "http://arxiv.org/abs/2405.14690"
doi: "https://doi.org/10.48550/arXiv.2405.14690"
toc: false
categories:
  - functional data analysis
  - hierarchical structure
  - continuous glucose monitoring
---

## Citation (APA)

> Matabuena, M., & Sartini, J. (2024). Multilevel functional data analysis modeling of human glucose response to meal intake. ArXiv.

## Abstract

Glucose meal response information collected via Continuous Glucose Monitoring (CGM) is relevant to the assessment of individual metabolic status and the support of personalized diet prescriptions. However, the complexity of the data produced by CGM monitors pushes the limits of existing analytic methods. CGM data often exhibits substantial within-person variability and has a natural multilevel structure. This research is motivated by the analysis of CGM data from individuals without diabetes in the AEGIS study. The dataset includes detailed information on meal timing and nutrition for each individual over different days. The primary focus of this study is to examine CGM glucose responses following patients' meals and explore the time-dependent associations with dietary and patient characteristics. Motivated by this problem, we propose a new analytical framework based on multilevel functional models, including a new functional mixed R-square coefficient. The use of these models illustrates 3 key points: (i) The importance of analyzing glucose responses across the entire functional domain when making diet recommendations; (ii) The differential metabolic responses between normoglycemic and prediabetic patients, particularly with regards to lipid intake; (iii) The importance of including random, person-level effects when modelling this scientific problem.
