---
title: "Glucose Color Index: Development and Validation of a Novel Measure of the Shape of Glycemic Variability"
type: "article"
author: "Sartini, Fang, Rooney, Selvin, Coresh, & Zeger"
year: "2024"
publication: "Diabetes Science and Technology"
doi: "https://doi.org/10.1177/19322968241245654"
materials: "https://journals.sagepub.com/doi/suppl/10.1177/19322968241245654/suppl_file/sj-docx-1-dst-10.1177_19322968241245654.docx"
toc: false
categories:
  - time series analysis
  - continuous glucose monitoring
  - periodogram
  - journal article
---

## Citation (APA 7)

> Sartini J, Fang M, Rooney MR, Selvin E, Coresh J, Zeger S. Glucose Color Index: Development and Validation of a Novel Measure of the Shape of Glycemic Variability. Journal of Diabetes Science and Technology. 2024;0(0). doi:10.1177/19322968241245654

## Abstract

Background: Standard continuous glucose monitoring (CGM) metrics: mean glucose, standard deviation, coefficient of variation, and time in range, fail to capture the shape of variability in the CGM time series. This information could facilitate improved diabetes management. Methods: We analyzed CGM data from 141 adults with type 2 diabetes in the Hyperglycemic Profiles in Obstructive Sleep Apnea (HYPNOS) trial. Participants in HYPNOS wore CGM sensors for up to two weeks at two time points, three months apart. We calculated the log-periodogram for each time period, summarizing using disjoint linear models. These summaries were combined into a single value, termed the Glucose Color Index (GCI), using canonical correlation analysis. We compared the between-wear correlation of GCI with those of standard CGM metrics and assessed associations between GCI and diabetes comorbidities in 398 older adults with type 2 diabetes from the Atherosclerosis Risk in Communities (ARIC) study. Results: The GCI achieved a test-retest correlation of R = .75. Adjusting for standard CGM metrics, the GCI test-retest correlation was R = .55. Glucose Color Index was significantly associated (p \< .05) with impaired physical functioning, frailty/pre-frailty, cardiovascular disease, chronic kidney disease, and dementia/mild cognitive impairment after adjustment for confounders. Conclusion: We developed and validated the GCI, a novel CGM metric that captures the shape of glucose variability using the periodogram signal decomposition. Glucose Color Index was reliable within participants over a three-month period and associated with diabetes comorbidities. The GCI suggests a promising avenue toward the development of CGM metrics which more fully incorporate time series information.
